apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devopsreplicacontrollers.example.com
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              selector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
              template:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      labels:
                        type: object
                        additionalProperties:
                          type: string
                  spec:
                    type: object
                    properties:
                      image:
                        type: string
                      pullSecretName:
                        type: string
                      config:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          required: ["name", "value"]
  scope: Namespaced
  names:
    plural: devopsreplicacontrollers
    singular: devopsreplicacontroller
    kind: DevopsReplicaController
    shortNames:
    - drc
