apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsreplicacontrolleroperator-deployment 
  labels:
    app: devopsreplicacontrolleroperator

spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsreplicacontrolleroperator

  template:
    metadata:
      name: devopsreplicacontrolleroperator-pod
      labels:
        app: devopsreplicacontrolleroperator
    spec:
      containers:
         - name: devopsreplicacontrolleroperator
           image: acradessodevopsagentsspeuw03.azurecr.io/devopsreplicacontrolleroperator:latest

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devopsreplicacontrolleroperator-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["example.com"]
  resources: ["devopsreplicacontrollers"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devopsreplicacontrolleroperator-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: devopsreplicacontrolleroperator-role
  apiGroup: rbac.authorization.k8s.io
